DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS searches CASCADE;
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	username VARCHAR(50) UNIQUE,
	email VARCHAR(50) UNIQUE,
	password_digest VARCHAR(255),
	issues VARCHAR(400)
);
CREATE TABLE searches(
	id SERIAL PRIMARY KEY,
	emailid INTEGER REFERENCES users(id),
	name VARCHAR(100),
	image TEXT
);
